# Generated by Django 3.2.11 on 2022-01-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image/%Y/%m/%d/'),
        ),
    ]
